# Generated by Django 5.1.2 on 2024-10-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low')], default='MEDIUM', max_length=10),
        ),
    ]
